sudo: false
language: python
python:
- '3.7'
- '3.8'
install: pip install tox-travis
script: tox
deploy:
  provider: pypi
  distributions: bdist_wheel
  user: "__token__"
  password:
    secure: lD13P7UHzgQErlzrkoI3EcPxI1l7tBfKaODwRWil9IIlwl0XR9FfLX2cFZfjJ5HPytlm7xTy1E6OxxZNS5HhBQkRakXejSJiI6P6N+ZiRlyCjwOChLe6TFMgqe9ufeyVajd1OO2bNCYMzKAxbsBJJiIf00iQmLoLuWxvlIhbDrAxvo2pdPKYX2296iji97Yco/aVcbtEguG5QtbcBJVX8EfCGwZKz45gNlCLudXEBKYw7FTOao5qzZ6z1MPC9UrrR00dAoxv+FhlAURQto6PvtF1hpJyW8SQuHfKJJAi33WAIMS96yhF1MdtkGqU6TU8eic7KG/5QNe2W/AEPAIaA0em/RDYUZ4kC0DKLwegQTUFA7cu88VepG6EPJlhk5uh3r5rorKxQXUSZBjmiknk1gPHMY7XjM5Oj6ER7M69LkyX1HAjy+L1EQ6zNNZ4glbH+SyhbXgdzUHwcAKqjUy+0OTKwJIEDmgk4ZG6+clwQrg3MzpJIAcwH8sFB+kBjCoqvf3VrhS0iiRAEwjHV8h824AKxlG7ISoOjwgtq40IUiieeBuKBWoPcNN/GzZAzSMylm5hGxMmfO9ABDcym8n/YlrQxzv2rF47uhKAw+WXy8WrjnD8i9itxrz6bGdBaWVOvgaIAek/Wth9GTAIsKwgoy+D206Mk4OyVlCvBmZ+9Ow=
  on:
    tags: true
    skip_existing: true
